# JVM mode base image for Java 21
FROM quay.io/quarkus/ubi-quarkus-jvm:2.16.4-java21

WORKDIR /app

# Copy Quarkus app output
COPY target/quarkus-app/ /app/

# Start the JVM-based Quarkus app
CMD ["java", "-jar", "quarkus-run.jar"]
